basePath: /
definitions:
  models.User:
    properties:
      created_at:
        type: string
      deleted_at:
        type: string
      id:
        type: integer
      updated_at:
        type: string
      username:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is an API for tracking orders.
  title: Order Tracking API
  version: "1.0"
paths:
  /register:
    post:
      consumes:
      - multipart/form-data
      description: Регистрирует нового пользователя с указанными username и password
      parameters:
      - description: Имя пользователя
        in: formData
        name: username
        required: true
        type: string
      - description: Пароль пользователя
        in: formData
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
      summary: Регистрация нового пользователя
      tags:
      - auth
swagger: "2.0"
